repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies: ["tomli"]
-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
        args:
          - --redact
-   repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.2
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-vet
      - id: go-test-mod
      - id: go-sec-mod
-   repo: local
    hooks:
      - id: frontend-type-check
        name: Frontend TypeScript type-check
        entry: npm run --prefix frontend lint
        language: system
        pass_filenames: false
        stages: [commit, push]
