// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {github} from '../models';
import {main} from '../models';

export function ApplyGovernanceActions(arg1:github.GovernanceActionRequest):Promise<github.GovernanceResponse>;

export function EnvironmentStatus():Promise<main.EnvironmentStatus>;

export function GetOrganizationSummary():Promise<main.RepoSummaryResponse>;

export function GetRepositoryDetail(arg1:string):Promise<main.RepoDetailResponse>;

export function GetSettings():Promise<main.SettingsPayload>;

export function ListRepositories(arg1:main.RepoListRequest):Promise<main.RepoListResponse>;

export function RefreshOrganizationSummary():Promise<main.RefreshSummaryResponse>;

export function SaveSettings(arg1:main.SettingsPayload):Promise<void>;
