// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyGovernanceActions(arg1) {
  return window['go']['main']['App']['ApplyGovernanceActions'](arg1);
}

export function EnvironmentStatus() {
  return window['go']['main']['App']['EnvironmentStatus']();
}

export function GetOrganizationSummary() {
  return window['go']['main']['App']['GetOrganizationSummary']();
}

export function GetRepositoryDetail(arg1) {
  return window['go']['main']['App']['GetRepositoryDetail'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListRepositories(arg1) {
  return window['go']['main']['App']['ListRepositories'](arg1);
}

export function RefreshOrganizationSummary() {
  return window['go']['main']['App']['RefreshOrganizationSummary']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
